repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]  # Incluye corrección específica para Markdown si lo usas.
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=88"]  # Ajusta el límite de longitud de línea si es necesario.

#  - repo: local
#    hooks:
#      - id: prettier-django-format
#        name: Prettier and djlint format
#        entry: ./format.sh
#        language: system
#        types: [file]
#        verbose: true  # Agrega verbosidad para un mejor diagnóstico en caso de problemas.
